apiVersion: v1
kind: ConfigMap
metadata:
  name: airbnb-config
  labels:
    app: airbnb
data:
  database-host: "airbnb-db-service"
  database-name: "airbnb"
  database-user: "postgres"
  backend-port: "5000"
  node-env: "production"
