apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secrets
  labels:
    app: airbnb
type: Opaque
data:
  # Base64 encoded values
  # database-password: postgrespassword
  database-password: cG9zdGdyZXNwYXNzd29yZA==
  # database-url: postgres://postgres:postgrespassword@airbnb-db-service:5432/airbnb
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3Jlczpwb3N0Z3Jlc3Bhc3N3b3JkQGFpcmJuYi1kYi1zZXJ2aWNlOjU0MzIvYWlyYm5i
